### ISSUE TITLE
browser not launching

### ISSUE THREAD

**Issue by bwanaaa** [iamdjones/sublime-text-browser-sync#10]
apple mac m1 
sublime text 3.2.2. 3211
browser sync installed through package control

I open an html file in sublime text and hit 'launch' under the browser sync menu--nothing happens.
I checked the 'browser_sync_launch.js' in the packages

var bs = require('browser-sync').create('ST3');

args = process.argv.slice(2);

bs.init({
	server:args[0],
	files:args[1].split(','),
	index:args[2],
	startPath:args[2],
	logLevel:"silent",
	browser:"chrome"
});

Chrome is installed.
I changed the last line to browser:"safari"
and still no go.

**Comment by bschwyn** [comment]
I'm having a similar issue, but am using chrome as my browser, and chrome is the default.

**Comment by GJThompson** [comment]
I am also having this issue.

**Comment by twnklwrnkl** [comment]
also having this issue

**Comment by abhinavprao** [comment]
same issue

**Comment by isaacflorez** [comment]
I am also having this issue. Hit launch and browser does not open. Latest version of sublime using chrome

**Comment by xy-fm** [comment]
I have the same issue. How to fix it?

**Comment by otezbigz** [comment]
same here I am Using sublime 4107 as well, browser sync is not reading my file and I cant lauch please need help your plugin is really precious to everyone

**Comment by samchadwick** [comment]
Using Sublime 4126.  Still seeing this issue.

**Comment by kaagaj-bottle** [comment]
the same issue even after clicking launch several times it does nothing
hope it will soon be solved

**Comment by ghost** [comment]
same

**Comment by turyabiswas233** [comment]
I also...
I think here is a bug on the update package. We should have to switch another package for live server.

**Comment by holliebutler** [comment]
Same issue.

**Comment by asimar007** [comment]
Same Issue

**Comment by Bless-Han** [comment]
same +1

**Comment by slopeware** [comment]
same issue

**Comment by Cruzstyle** [comment]
same issue

**Comment by iamdjones** [comment]
archiving project
