### ISSUE TITLE
Doesn't work on Ubuntu 14.04

### ISSUE THREAD

**Issue by saintplay** [iamdjones/sublime-text-browser-sync#4]
Hello, I tested this plugin on Windows and works amazing, however in my Ubuntu 14.04 doesn't work at all. I already have installed node.js.
Every time I try to launch the sublime console give me this error " /bin/sh: 1: node-linux: not found "

![selection_001](https://cloud.githubusercontent.com/assets/9372893/11878715/71da88b6-a4c5-11e5-8bee-c2f7baf996d8.png)

How can I fix that?

**Comment by iamdjones** [comment]
A version of node is shipped with the plugin. if you look in the root of the repo, node-linux is sitting right there. Obviously i should have marked this as a windows only plugin before shipping and then once implemented add linux and osx. Just checked and the current directory isn't prepended to the call to node-linux which is required for calling commands not found in the path.  
https://github.com/iamdjones/sublime-text-browser-sync/blob/523be9f52ad37bf587c92d4dea3637f6ae6f2b3e/browser_sync.py#L88
