### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by kleninb** [iamdjones/sublime-text-browser-sync#5]
This plugin worked fine on Windows 10 but when I tried to use the same plugin to launch files on Mac. Nothing is happening, no response.

**Comment by Andergraw** [comment]
Same here.
I think it's something related to [this](https://github.com/iamdjones/sublime-text-browser-sync/issues/4) but it looks like this repo is pretty abandoned...

**Comment by ForestedDev** [comment]
@Andergraw i do believe it has been abandoned, last commit 2015

**Comment by Andergraw** [comment]
Yes, I never used it. Looked for an alternative (LiveReload)

**Comment by ForestedDev** [comment]
@Andergraw i tried that, it worked but i still prefered browsersync if i could get it. if you use sublime you could get a working browsersync from packagecontrol

**Comment by Andergraw** [comment]
DId you manage to get it working?
In the end I was happy enough with LiveReload...

**Comment by mariosdaskalas** [comment]
Anyone get it working on Windows 10 64 bit?

**Comment by StudioMontt** [comment]
> ¿Alguien lo hizo funcionar en Windows 10 de 64 bits?

si, yo en Windows 10 y ahora en Windows 11... funciona de maravilla... le falta un poco de mas opciones, como para cambiar el puerto y poder cerrarlo fácil, pero está bien.

**Comment by richappow** [comment]
how do you set up LiveReload and LiveServer

**Comment by mariosdaskalas** [comment]
Found no way to do that. Repo is 8 years old with no updates. Maybe look somewhere else or use VS Code.

**Comment by iamdjones** [comment]
archiving project
