### ISSUE TITLE
Suggestion! Please see!

### ISSUE THREAD

**Issue by vanja-san** [iamdjones/sublime-text-browser-sync#6]
Please add **more settings**, example:
  - **Browser** selection
  - **Stop** button
  - **Port** selection
  - etc.

**Comment by Sufia-TheSecureDev** [comment]
> Please add **more settings**, example:
> 
> * **Browser** selection
> * **Stop** button
> * **Port** selection
> * etc.

could u tell me please  !  how can i work with  browser sync  for a php file??

**Comment by iamdjones** [comment]
archiving project
