### ISSUE TITLE
Browser sync keeps opening the html file in chrome and i want to chrome.

### ISSUE THREAD

**Issue by abhishekdam** [iamdjones/sublime-text-browser-sync#7]
Browser sync keeps opening the html file in chrome and i want to chrome. And I seriously it to firefox, but I couldnt find anything in the internet so I am directly asking you sir, and also thank you sir for making this package, it has made web designing a lot much easier, thanks alot sir.
Also sir i wanted to ask that sir, after using the package for the first time after launching the sublime text I am not able to use it the second time, I think it crashes after the first use, so can you help me in anyway with this problem.
thank you in advance.

**Comment by StudioMontt** [comment]
Para detener el servidor puedes hacerlo del Administrador de Tareas, buscas "Evented I/O for V8 JavaScript" y lo detienes. Espero sirva aún! Yo lo sigo usando y es genial!

**Comment by StudioMontt** [comment]
> El funcionamiento del navegador sigue abriendo el archivo html en Chrome y quiero Chrome. Y lo digo en serio en Firefox, pero no pude encontrar nada en Internet, así que le pregunto directamente, señor, y también gracias, señor, por hacer este paquete, ha facilitado mucho el diseño web, muchas gracias, señor. También señor, quería preguntarle a ese señor, después de usar el paquete por primera vez después de iniciar el texto sublime, no puedo usar la segunda vez, creo que falla después del primer uso, así que ¿puede ayudarme de todos modos? este problema. gracias de antemano.

Para detener el servidor puedes hacerlo del Administrador de Tareas, buscas "Evented I/O for V8 JavaScript" y lo detienes. Espero sirva aún! Yo lo sigo usando y es genial!
