### ISSUE TITLE
How do you terminate BrowserSync?

### ISSUE THREAD

**Issue by Alzy** [iamdjones/sublime-text-browser-sync#8]
I installed the plugin and all seemed well but now BrowserSync is permanently running in the background with no option to terminate it. When the plugin is run through Sublime Text a console window opens momentarily then disappears. Normally I'd Ctrl+C in my browser sync console to terminate it but that is not present in this plugin

**Comment by shardul-b** [comment]
In my case I had to forcefully stop the port from command prompt.

**Comment by StudioMontt** [comment]
Puedes hacerlo del Administrador de Tareas, buscas "Evented I/O for V8 JavaScript" y lo detienes. Espero sirva aún!

**Comment by open-codebranch** [comment]
> In my case I had to forcefully stop the port from command prompt.

It gets the job done. But, Is it the right way?

**Comment by StudioMontt** [comment]
Not ideal, but there is no other option. Unfortunately there has been no update. Still the best I've ever had.

**Comment by iamdjones** [comment]
archiving project
